### ISSUE TITLE
Fails on my Magento 1.9.2.2 site

### ISSUE THREAD

**Issue by phillipmeyer** [cardstream/magento-hosted-module#3] opened 2017-05-23 09:06 UTC
When we install this extension, it crashes whenever we click ‘Proceed to checkout’ from our basket page with the following error:
/var/www/html/app/code/community/Cardstream/PaymentGateway/Model/Standard.php on line 166

Looking at the code in your extension, I can see the following:
        $amount = $quote->getTotals()['grand_total']->getValue() * 100;

I am not a developer but I don’t think that getTotals()[‘grand_total’] is a valid call to get the grand total, I think it should be something like the following but I’m not totally sure:
        $amount = $quote->getGrandTotal()->getValue() * 100;

Also, if I make this change, then I get the same error on a different page:
Parse error: syntax error, unexpected '[' in /var/www/html/app/code/community/Cardstream/PaymentGateway/controllers/OrderController.php on line 77

**Comment by wilsonc93** [comment] 2017-05-23 09:37
Hi,

Thank you for your feedback. This is being investigated and we hope to have a resolution out as soon as possible.

Regards,
Chris

**Comment by Quacky2200** [comment] 2017-05-25 09:58
Hi Philip, 

Thanks for your email. If possible I would like to try and get this sorted here since it will be easier to contact each other.

To answer your questions:

1. I have two sets of settings in Magento ‘Cardstream Payment Gateway’ and ‘Cardstream hosted Gateway’, which of those two should I activate? (I have tried them all but none work right now)
**You should be using 'Cardstream Payment Gateway' which is the newest of both. I have amended this in the latest commit.**

**Since I assume that you're copying these files, it might be good to try and delete the following so that you have purged CardstreamHosted and the old template (if it still exists before you have moved it) from your setup to avoid any confusion**

```
httpdocs/app/code/community/Cardstream/CardstreamHosted
httpdocs/app/etc/modules/Cardstream_CardstreamHosted.xml
httpdocs/app/design/frontend/default/default/template/CardstreamHosted
httpdocs/app/design/frontend/default/template/PaymentGateway
```

2. I would love to use the ‘direct’ method but I notice that it requires the customer to enter their billing address again, surely this should be picked up from the Magento order? Why does it ask for this to be entered again?
**My [latest commit](https://github.com/cardstream/magento-hosted-module/commit/726ccb5b99094e26632914c5fdf4cac764a373ac) adds this change.**

3. Once a customer finalises our one page checkout process and after ‘submitting order’ I am just transferred to a blank page.

The page it is directed to which is failing is: /cardstream/order/process/ 

There is nothing in the Magento exception.log or the apache error log but in the Magento system.log I am seeing these errors which I believe is the cause:
```
2017-05-24T16:25:07+00:00 CRIT (2): Not valid template file:frontend/base/default/template/PaymentGateway/Hosted.phtml
2017-05-24T16:25:13+00:00 CRIT (2): Not valid template file:frontend/base/default/template/PaymentGateway/Hosted.phtml
```

Looking at your code, this template is actually saved under the app/design/frontend/rwd/default/template folder which appears to be an error. I have created the folder and made a copy of the files in app/design/frontend/base/default/template/PaymentGateway and then it appears to work.

Can you confirm that this is the correct solution and I have not missed something?
**This might just be due to the template being used on the website. I've seen that Magento 1.9 consistently uses base for templates so I have moved this in the latest commit. We didn't get this bug because we do not load a custom theme when testing this module**

**However the template files are only used during the checkout process (selection of payment option) and is not part of the redirect URL `/cardstream/order/process`. I'm not sure exactly why your magento install cannot find the page, The URL should be accessing it like so {module base name}/{controller name}/{action}**


4. I tried using your test merchant ID (100001) and the merchant ID you gave me 108173 to place a test order in our system but the payment seems to fail with the following error:
ERROR: 66343 - ERROR CODE (RC_INVALID_SIGNATURE)

I am using the signature Key ‘Pine50Mental16Spray’ under 'Merchant Shared Key’, this was given to me by Jack Leat. Is this correct or do I have to set something else up in your ‘MMS’ as suggested by the README file?

**The test merchant ID 100001 is used with the signature key Circle4Take40Idea and merchant ID 1081773 with Pine50Mental16Spray**

5. I cannot access the MMS as even though I have sent in the direct debit form, it blocks me and keeps requesting card details. Can this be resolved.
**I'm a bit unsure what you mean here, This is using the direct method?**

**Comment by phillipmeyer** [comment] 2017-05-25 12:52
Hi,

Thank you for trying to help. We are definitely making progress.

1. I’m not totally sure if Hosted is working or not.
If I go through the process with the hosted method using your test merchant ID (100001) and Signature Key of ‘Circle4Take40Idea’, then I get the following error when I’m returned to my site (it had a similar error on the cardstream page but I wasn’t quick enough to screen shot it).

Sorry, we are unable to process this order (reason: ERROR CODE (RC_INVALID_CARDNUMBER)). Please correct any faults and try again.

But it definitely populated the name, address, etc and took my card details. Is there  a special card number to use for the test merchant id, one that will ‘authorise’?
I used one of my cards for testing so I am guessing it might just be that it doesn’t work with normal cards so as not to charge them? (That’s how sagepay testing works)


2. However, I then tried to use my merchant ID and signature key that was supplied by Jack. For reference this is the CARDSTREAM merchant ID and not the one I was issued by CashFlows, they are different, does that matter? I would have thought they should be the same?

Merchant ID 108173
Signature Key of Pine50Mental16Spray

This is the error I get when I am directed to cardstream.
Could this be because I’m still waiting for them to sort out the direct debit? The ‘MMS’ I referred to in my previous email is your web based user interface that doesn’t let me access because they still haven’t set up my DD (it just asks for a credit card each time I log in)




3. However, I don’t have any luck at all if I use the direct method (which I would prefer):
Firstly the address and customer name isn’t being populated correctly, this is what I see:



Then I am getting a blank page (only with the direct method) when I get to https://www.metsuki.com/cardstream/order/process/ <https://www.metsuki.com/cardstream/order/process/> but there is no error reported in the log file. 
(I deleted the files you mentioned and have re-uploaded the new version from GitHub)
So there seems to be a new issue relating to direct.

I’m actually happy to stick with hosted until we get things working and maybe get direct working later?



4. One other issue that I have now discovered. In the settings, I can only make changes at Magento 'website' and ‘shop’ level, not ‘shop view’ level.
I accept multiple currencies and have a different ‘shop view’ level for each country. In theory this would allow me to translate the site for multiple languages but in fact I use it to target different currencies and show different content.
However, I cannot change the currency at this level which I would need to do, otherwise we are likely to send you dollar amounts (for example) when you think you are getting GBP.
Does this make sense?

Regards,

Phillip.

**Comment by Quacky2200** [comment] 2017-05-25 13:14
Hi Philip,

I noticed what you meant with the blank page just after I had responded to you so I worked on trying to fix any issues and test them more before committing them again. I decided to upload now under this commit. From my tests they are stable but it's not always as simple. This commit should hopefully fix the blank page and some of the little bugs with Direct and Hosted. I also saw I was able to access `/cardstream/order/process` from your website which was unavailable before, so yes, I think we are getting somewhere and it would be a good idea to test this again.

We do not offer test information other than the test merchant ID and signature. You should have been given (should should be able to ask for) a test card/account which should allow you to test it properly from CashFlows. Due to this, I think it'll be a good idea to refer you to Jack (by email) as he will be able to help you with the MMS too.

When you use shop view, do the currencies automatically change? If I can find out if Magento is compatible I will try to integrate this as I assume that I should be able to automatically get the currency code for this purpose.

**Comment by phillipmeyer** [comment] 2017-05-25 13:26
Hi,

Thank you. I have asked Jack to help re. merchant ID.

Can you confirm, do I need to download something else from GitHub and test it? I’m going to be out for a few hours now so it may have to be tomorrow.

Also, do you know what the error was I received? Was this just that it didn’t like my card or was there a wider issue:
Sorry, we are unable to process this order (reason: ERROR CODE (RC_INVALID_CARDNUMBER)). Please correct any faults and try again.

Finally, with the currencies. When we change shop view, each shop view has a currency set in Magento SYSTEM - CONFIGURATION - CURRENCY SETUP
I have a base currency which is our local currency, then a ‘default display currency’.
For each store view I have a different ‘default display currency’ and although I could allow the customer to change currency within a store view, I don’t and I have those fixed. (I have attached screen shots)

What I was expecting was to be able to adjust the currency code for each store view so that I could select a currency.

I’m not sure we can use CashFlows unless this works, I think with SagePay it sends the base currency and display currency and if you only have one currency set-up in sagepay then they just charge the base currency value.








Regards,

Phillip.

**Comment by Quacky2200** [comment] 2017-05-25 13:57
The [new commit](https://github.com/cardstream/magento-hosted-module/commit/1fea08c8ead06257df3077688f39a7330babaa3b) will need to be [downloaded](https://github.com/cardstream/magento-hosted-module/archive/1fea08c8ead06257df3077688f39a7330babaa3b.zip) so that we can see if this solves your issues. It's no issue if we have to wait until tomorrow.

Yes, RC_INVALID_CARDNUMBER is probably due to using a test merchant with a live card but that should disappear when you and Jack are able to correct the small problems setting up merchant and testing transactions. If you haven't already it would be a good idea to ask any questions you may have about CashFlows integration with Jack.

I will look into the potential integration of multiple currencies.

**Comment by phillipmeyer** [comment] 2017-05-26 14:23
Hi Matthew,

I can put a transaction through with the test merchant account and a test card and the whole process works perfectly, it authorises and directs back to my website with a successful purchase.

However, when I use my merchant account it doesn’t work :-(

Here is what I get and my settings are shown below, I cannot see why the test account would work and mine doesn’t? (I used my companies debit card for the transaction).

By the way, I hadn’t realised but I think this is publishing our conversation on GitHub and sharing them with other subscribers on GitHub, is it possible to make some of the historic emails private? (For example my company details, account numbers, etc). I think we have published my merchant accounts and the signature key in these emails.






Regards,

Phillip.

**Comment by Quacky2200** [comment] 2017-05-26 16:14
Hi Philip,

I'm glad that we've got one part working successfully. Since you have been replying via email I have had to remove any confidential information. Sadly email replies don't embed the images you send either. Information you provide to Cardstream is confidential and is typically sent via emails as you had done previously. GitHub issues are aimed at solving module issues so private information is never to be provided here.

If you could possibly reattach the image either to the original ticket by email or in GitHub via a browser following the rules above; that would help greatly.

Regards

**Comment by phillipmeyer** [comment] 2017-05-26 18:27
Hello,

I also connected with Jack and it appears to be a cashflows error, he has
contacted them for me.

It looks like this should be working now, he only concern I have is the
ability to change currency. As an alternative, will your extension just
charge the base currency, not the default store currency?

Regards,

Phillip.


Sent from my iPhone

On 26 May 2017, at 17:14, Matthew James <notifications@github.com> wrote:

Hi Philip,

I'm glad that we've got one part working successfully. Since you have been
replying via email I have had to remove any confidential information. Sadly
email replies don't embed the images you send either. Information you
provide to Cardstream is confidential and is typically sent via emails as
you had done previously. GitHub issues are aimed at solving module issues
so private information is never to be provided here.

If you could possibly reattach the image either to the original ticket by
email or in GitHub via a browser following the rules above; that would help
greatly.

Regards

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/cardstream/magento-hosted-module/issues/3#issuecomment-304324028>,
or mute the thread

**Comment by Quacky2200** [comment] 2017-05-30 16:15
Hi Philip,

Sorry for the delayed response. I have been in a meeting and as such cannot work on this until tomorrow where I will give this my full attention.

Regards

**Comment by phillipmeyer** [comment] 2017-05-30 17:51
Thank you!

Regards,

Phillip.

**Comment by phillipmeyer** [comment] 2017-05-31 08:51
Hi Matthew,

In follow up to my previous email. I would be happy if (as an initial step) the extension could simply take the basket value in the base currency (rather than the current default display currency). I know that Magento makes that value in the base currency available. Then the customer would be charged in sterling but they would be charged the correct amount.

I think that the ebizmarts SagePay extension works this way, depending on one of the variables you setup in their admin. I’d be happy to show you how that works if it would help, perhaps we can screen share via Skype?

Regards,

Phillip.

**Comment by Quacky2200** [comment] 2017-05-31 09:32
Hi Philip, 

I think I understand what you are asking for, I have put an example below

```
$baseCurrencyCode = Mage::app()->getStore()->getBaseCurrencyCode(); 
$currentCurrencyCode = Mage::app()->getStore()->getCurrentCurrencyCode();
$price = 100;
 
// convert price from current currency to base currency
$priceOne = Mage::helper('directory')->currencyConvert($price, $currentCurrencyCode, $baseCurrencyCode); 
 
// convert price from base currency to current currency
$priceTwo = Mage::helper('directory')->currencyConvert($price, $baseCurrencyCode, $currentCurrencyCode); 
```

Regards

**Comment by phillipmeyer** [comment] 2017-05-31 09:48
Hi,

I had a quick look on google and it seems that although the basket value in the base currency is stored somewhere in Magento it’s not automatically available.

I’m not an expert developer (although I have a good understanding of php and Magento) so I think your example is probably the right approach if we simply convert the display currency to the base currency for checkout.

It might be worth displaying both values somewhere in the checkout process (if possible) so as not to surprise the customer once they are passed through to cardstream and see the GBP amount.

SagePay do this by showing something like:

Total cost $300
(Store currency £200)  <<smaller font

Regards,

Phillip.

**Comment by Quacky2200** [comment] 2017-05-31 10:58
Hi Philip,

I looked into this. It seems like a simple fix should help you. In the latest commit I have simply added the value `<show_in_store>1</show_in_store>` in the necessary places of the system.xml. After making sure that Magento refreshes (reset any required cache or indexes), you'll be able to configure the modules currency in different stores. I have modified this for you in the recent commit and have tested it with three test stores, UK, European and United States and have been able to see the currency change in each and afterwards, get represented in the form upon checkout. What you should be able to do is install the new module and make sure that the page properly refreshes. You should be able to go into each store and set a different currency. It would be a good idea to check that the currency changes on the hosted form for each store.

Since this changes the currency automatically we shouldn't have to convert with exchange rates.

Hopefully this solves your issue. Let me know if it's still an issue

Regards.

**Comment by phillipmeyer** [comment] 2017-05-31 13:14
Hi,

That worked perfectly and was what I had originally meant for you to do but I didn’t necessarily explain myself well. Thanks!

Regards,

Phillip.

**Comment by Quacky2200** [comment] 2017-05-31 13:47
That's great to hear. I'm glad it's what you wanted.

Now that your problem has been resolved, I will close this issue for you.

Regards

**Closed by Quacky2200** 2017-05-31 13:47 UTC
